### ISSUE TITLE
Option to backup database as zip file

### ISSUE THREAD

**Issue by KevinSleegers** [dyerc/capistrano-craft#4]
Hi,

At the moment a backup of the database is made during every deploy. This is a sql file that can be quite large. Craft CMS has the option to export the backup as a zip file via `db/backup --zip=1` which makes the file considerably smaller. Is it possible to add this as an option?

Kind regards,
Kevin

**Comment by dyerc** [comment]
Thanks very much for mentioning this @KevinSleegers 

I think this could just become the default since the control panel backup command within Utilities always seems to produce a zip file.

This update should be released in version 0.3.6
